global:
  scrape_interval: 15s # How often to scrape targets by default.

scrape_configs:
  - job_name: "online_bookstore"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets:
          - "host.docker.internal:8080" # Replace with the hostname or IP of your app
